// Catch-all route for /api/* — without this filename, Vercel's `api/`
// directory convention only routes the exact path /api to api/index.ts,
// leaving /api/v1/* unmapped (404 from the edge before the Function runs).
// @ts-ignore — _bundle.mjs is generated by scripts/build-api.mjs at build time
export { default } from "./_bundle.mjs";
